---
- name: stigrule_214273_latestversion
  ansible.builtin.dnf:
    name: httpd
    state: latest
    update_cache: true
- name: Update template and copy to destination server
  ansible.builtin.template:
    src: templates/chrony.conf.j2
    dest: /etc/chrony.conf
    owner: root
    group: root
    mode: 0644
    backup: true
- name: stigrule_214228_keepalive
  ansible.builtin.lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regexp: '(?i)^KeepAlive\s+Off'
    line: '{{ apache24STIG_stigrule_214228_http_conf_keepalive_Line }}'
    create: yes
  when:
    - apache24STIG_stigrule_214228_Manage
- name: stigrule_214228-2_keepalive
  ansible.builtin.lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regexp: '(?i)^MaxKeepAliveRequests\s+[0-9]*'
    line: '{{ apache24STIG_stigrule_214228_2_http_conf_MaxKeepAlive_Line }}'
    create: yes
  when:
    - apache24STIG_stigrule_214228_2_Manage
- name: stigrule_214242_erasemanuals
  ansible.builtin.dnf:
    name: httpd-manual
    state: absent
- name: stigrule_214242_welcome
  ansible.builtin.copy:
    src: templates/welcome.conf.j2
    dest: /etc/httpd/conf.d/welcome.conf
    owner: root
    group: root
    mode: 644
- name: stigrule_214253_module_check
  ansible.builtin.command:
    cmd: httpd -M | grep unique_id
    rc: 1
    register: unique_id_exists
- name: stigrule_214253_uniqueid
  ansible.builtin.copy:
    src: templates/uniqueid.conf.j2
    dest: /etc/httpd/conf.modules.d/00-unique_id.conf
  when: unique_id_exists
- name: Restart and enable chrony daemon
- name: stigrule_214229_module_check
  ansible.builtin.command:
    cmd: httpd -M | grep 'session_module|usertrack'
    rc: 1
    register: usertrack_exists
- name: stigrule_214229_usertrack
  ansible.builtin.copy:
    src: templates/usertrack.conf.j2
    dest: /etc/httpd/conf.modules.d/00-usertrack.conf
  when: usertrack_exists
- name: Restart and enable httpd daemon
  ansible.builtin.service:
    name: httpd
    state: restarted
    enabled: true
