---
- name: Install latest version of chrony
  ansible.builtin.dnf:
    name: chrony
    state: latest
    update_cache: true
- name: Update template and copy to destination server
  ansible.builtin.template:
    src: templates/chrony.conf.j2
    dest: /etc/chrony.conf
    owner: root
    group: root
    mode: 0644
    backup: true
- name: stigrule_214228_keepalive
  ansible.builtin.lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regexp: '(?i)^KeepAlive\s+Off'
    line: '{{ apache24STIG_stigrule_214228_http_conf_keepalive_Line }}'
    create: yes
  when:
    - apache24STIG_stigrule_214228_Manage
- name: stigrule_214228-2_keepalive
  ansible.builtin.lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regexp: '(?i)^MaxKeepAliveRequests\s+[0-9]*'
    line: '{{ apache24STIG_stigrule_214228_2_http_conf_MaxKeepAlive_Line }}'
    create: yes
  when:
    - apache24STIG_stigrule_214228_2_Manage
- name: stigrule_214242_erasemanuals
  ansible.builtin.dnf:
    name: httpd-manual
    state: absent
- name: stigrule_214242_welcome
  ansible.builtin.copy:
    src: templates/welcome.conf.j2
    dest: /etc/httpd/conf.d/welcome.conf
    owner: root
    group: root
    mode: 644
- name: Restart and enable chrony daemon
  ansible.builtin.service:
    name: chronyd
    state: restarted
    enabled: true
