---
- name: Install latest version of chrony
  ansible.builtin.dnf:
    name: chrony
    state: latest
    update_cache: true
- name: Update template and copy to destination server
  ansible.builtin.template:
    src: templates/chrony.conf.j2
    dest: /etc/chrony.conf
    owner: root
    group: root
    mode: 0644
    backup: true
- name: stigrule_214228_keepalive
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regexp: "(?i)^KeepAlive\s+Off"
    line: "{{ apache24STIG_stigrule_214228_http_conf_keepalive_Line }}"
    create: yes
  when:
    - apache24STIG_stigrule_214228_Manage
- name: Restart and enable chrony daemon
  ansible.builtin.service:
    name: chronyd
    state: restarted
    enabled: true
