---
- name: stigrule_214273_latestversion
  ansible.builtin.dnf:
    name: httpd
    state: latest
    update_cache: True
- name: stigrule_214228_keepalive
  ansible.builtin.lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regexp: '(?i)^KeepAlive\s+Off'
    line: '{{ apache24STIG_stigrule_214228_http_conf_keepalive_Line }}'
    create: yes
  when:
    - apache24STIG_stigrule_214228_Manage
- name: stigrule_214228-2_keepalive
  ansible.builtin.lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regexp: '(?i)^MaxKeepAliveRequests\s+[0-9]*'
    line: '{{ apache24STIG_stigrule_214228_2_http_conf_MaxKeepAlive_Line }}'
    create: yes
  when:
    - apache24STIG_stigrule_214228_2_Manage
- name: stigrule_214242_erasemanuals
  ansible.builtin.dnf:
    name: httpd-manual
    state: absent
- name: stigrule_214242_welcome
  ansible.builtin.copy:
    src: templates/welcome.conf.j2
    dest: /etc/httpd/conf.d/welcome.conf
    owner: root
    group: root
    mode: 644
- name: stigrule_214253_module_check
  ansible.builtin.command:
    cmd: httpd -M | grep unique_id
    rc: 1
    register: unique_id_exists
- name: stigrule_214253_uniqueid
  ansible.builtin.copy:
    src: templates/uniqueid.conf.j2
    dest: /etc/httpd/conf.modules.d/00-unique_id.conf
  when: unique_id_exists
- name: stigrule_214229_module_check
  ansible.builtin.command:
    cmd: httpd -M | grep 'session_module|usertrack'
    rc: 1
    register: usertrack_exists
- name: stigrule_214229_usertrack
  ansible.builtin.copy:
    src: templates/usertrack.conf.j2
    dest: /etc/httpd/conf.modules.d/00-usertrack.conf
  when: usertrack_exists
- name: Restart and enable httpd daemon
- name: stigrule_214230_module_check
  ansible.builtin.command:
    cmd: httpd -M | grep ssl_module
    rc: 1
    register: ssl_exists
- name: stigrule_214230_ssl
  ansible.builtin.dnf:
    name: mod_ssl
    state: latest
    update_cache: True
- name: stigrule_214230_2_ssl
  ansible_builtin.lineinfile:
    path: /etc/httpd/conf.d/ssl.conf
    regexp: '(?i)SSLProtocol'
    line: '{{ apache24STIG_stigrule_214230_2_ssl_Line }}'
  when:
    - apache24STIG_stigrule_214230_2_Manage
- name: stigrule_214231_CustomLog
  ansible.builtin.lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regexp: '(?i)^CustomLog*'
    line: '{{ apache24STIG_stigrule_214231_CustomLog_Line }}'
    create: yes
  when:
    - apache24STIG_stigrule_214231_Manage
- name: stigrule_214246_Listen
  ansible.builtin.lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regexp: '(?i)^Listen\s+80'
    line: 'Listen {{ apache24STIG_stigrule_214228_ListenAddress_Line }}'
- name: stigrule_214250_SessionAge
  ansible.builtin.lineinfile:
    path: /etc/httpd/conf/httpd.conf
    insertbefore: '(?i)^#\s+Supplemental\s+configuration'
    line: '{{ apache24STIG_stigrule_214250_SessionAge_Line }}'
  when: apache24STIG_stigrule_214250_Manage
- name: stigrule_214252_SessionCryptoCipher
  ansible.builtin.lineinfile:
    path: /etc/httpd/conf/httpd.conf
    insertbefore: '(?i)^#\s+Supplemental\s+configuration'
    line: '{{ apache24STIG_stigrule_214252_SessionCrypto_Line }}'
  when: apache24STIG_stigrule_214252_Manage
- name: stigrule_214255_Timeout
  ansible.builtin.lineinfile:
    path: /etc/httpd/conf/httpd.conf
    insertbefore: '(?i)^#\s+Supplemental\s+configuration'
    line: '{{ apache24STIG_stigrule_214255_Timeout_Line }}'
  when: apache24STIG_stigrule_214255_Manage
- name: stigrule_214257_TraceEnable
  ansible.builtin.lineinfile:
    path: /etc/httpd/conf/httpd.conf
    insertbefore: '(?i)^#\s+Supplemental\s+configuration'
    line: '{{ apache24STIG_stigrule_214257_TraceEnable_Line }}'
  when: apache24STIG_stigrule_214257_Manage
- name: stigrule_214267_permissions
  ansible.builtin.file:
    path: /run/httpd/httpd.pid
    owner: root
    group: root
    mode: '0644'
- name: stigrule_214269_CipherSuite
  ansible_builtin.lineinfile:
    path: /etc/httpd/conf/httpd.conf
    insertbefore: '(?i)^#\s+Supplemental\s+configuration'
    line: '{{ apache24STIG_stigrule_214269_CipherSuite_Line }}'
  when:
    - apache24STIG_stigrule_214269_Manage
- name: restart httpd service
  ansible.builtin.service:
    name: httpd
    state: restarted
    enabled: true
